### ISSUE TITLE
Expose all parameters in ValueCallback and DataSource functions

### ISSUE THREAD

**Issue by lukasberbuer** [open62541pp/open62541pp#515]
Following parameters of the nodestore plugins `UA_ValueCallback` and `UA_DataSource` are currently **not** forwarded from open62541, which might be required in some cases (#462):
- `UA_Server* server`
- `UA_NodeId* sessionId`
- `void* sessionContext`
- `UA_NodeId* nodeId`
- (`const UA_NumericRange* range`, missing in `ValueCallback` functions)

See: https://github.com/open62541/open62541/blob/v1.4.8/include/open62541/plugin/nodestore.h#L423-L533

### Todos
- [x] Add `nodeId` to `opcua::ValueBackendDataSource` functions (#462)
- [x] Add `nodeId` to `opcua::ValueCallback` functions. (#516)
- [x] Both `server` and `sessionId` could be wrapped in a `opcua::Session` object and passed to the callback functions. (#522, #525)
- [x] The `range` is passed by reference to `opcua::ValueBackendDataSource` although it is an optional parameter. It should be passed by pointer instead. (#517)
- [x] Add `range` parameter to `opcua::ValueCallback` functions. (#518)
